project:
  type: website

website:
  title: "Kylie Vento"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Resume"
        href: resume.qmd
    right:
      - icon: github
        href: https://github.com/kvent-stack
format:
  html:
    theme: pulse

